In [2]:
import numpy as np

In [6]:
# soru : 2 
arr1 = np.arange(34,113,6)
arr1

array([ 34,  40,  46,  52,  58,  64,  70,  76,  82,  88,  94, 100, 106,
       112])

In [4]:
# soru : 4 
arr2 = np.logspace(2,5 ,8)
arr2

array([   100.        ,    268.26957953,    719.685673  ,   1930.69772888,
         5179.47467923,  13894.95494373,  37275.93720315, 100000.        ])

In [66]:
# soru : 3
arr3 = np.linspace(50,500,91 , dtype = int)
arr3 

array([ 50,  55,  60,  65,  70,  75,  80,  85,  90,  95, 100, 105, 110,
       115, 120, 125, 130, 135, 140, 145, 150, 155, 160, 165, 170, 175,
       180, 185, 190, 195, 200, 205, 210, 215, 220, 225, 230, 235, 240,
       245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295, 300, 305,
       310, 315, 320, 325, 330, 335, 340, 345, 350, 355, 360, 365, 370,
       375, 380, 385, 390, 395, 400, 405, 410, 415, 420, 425, 430, 435,
       440, 445, 450, 455, 460, 465, 470, 475, 480, 485, 490, 495, 500])

In [5]:
# soru: 5 
soru5 = np.arange(0,9)
soru5.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
# soru : 1
soru1 = np.array([[[1,2,3,4] , [10,11,12,13,]] , [[13,14,15,16] , [100,200,300,400]]])
soru1

array([[[  1,   2,   3,   4],
        [ 10,  11,  12,  13]],

       [[ 13,  14,  15,  16],
        [100, 200, 300, 400]]])

In [25]:
soru1.ndim

3

In [28]:
# soru : 6 
np.zeros((6,6), dtype= int )

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [30]:
# soru : 7
np.ones((4,4) , dtype= int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
# soru : 8 
np.eye(8,8, dtype= int)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

In [35]:
# soru : 9
np.eye(5,5, dtype=int) * 3

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [38]:
# soru : 10 
np.linspace(0,1,6 , dtype=float)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [52]:
# soru : 11
soru11 = np.random.randint(50,101,10)
soru11

array([99, 71, 70, 64, 80, 99, 98, 58, 65, 90])

In [59]:
soru11.reshape((5,2))

array([[99, 71],
       [70, 64],
       [80, 99],
       [98, 58],
       [65, 90]])

In [93]:
# soru : 12
soru12 = np.logspace(2,3,50 ,dtype=int)
soru12

array([ 100,  104,  109,  115,  120,  126,  132,  138,  145,  152,  159,
        167,  175,  184,  193,  202,  212,  222,  232,  244,  255,  268,
        281,  294,  308,  323,  339,  355,  372,  390,  409,  429,  449,
        471,  494,  517,  542,  568,  596,  625,  655,  686,  719,  754,
        790,  828,  868,  910,  954, 1000])

In [61]:
soru12.reshape(2,5,5)

array([[[ 100,  104,  109,  115,  120],
        [ 126,  132,  138,  145,  152],
        [ 159,  167,  175,  184,  193],
        [ 202,  212,  222,  232,  244],
        [ 255,  268,  281,  294,  308]],

       [[ 323,  339,  355,  372,  390],
        [ 409,  429,  449,  471,  494],
        [ 517,  542,  568,  596,  625],
        [ 655,  686,  719,  754,  790],
        [ 828,  868,  910,  954, 1000]]])

In [90]:
# soru 13 
soru13 = np.random.randint(0,101,10)
soru13

array([16, 55, 49, 49, 77, 28, 36, 72, 82, 72])

In [91]:
print(soru13.max())
print(soru13.min())
print(soru13.argmax())
print(soru13.argmin())

82
16
8
0


In [138]:
# soru : 14
soru14 = np.random.randint(300,502,20, dtype=int)
soru14

array([415, 324, 388, 382, 476, 343, 455, 308, 451, 353, 466, 460, 460,
       468, 332, 339, 430, 477, 495, 493])

In [149]:
soru14 = np.random.randn(2,2,5)
soru14

array([[[ 2.01471125,  1.38969186, -0.63074962, -0.15529825,
          0.21497829],
        [-0.24099829, -0.28800169,  0.85892976, -0.21437859,
          0.03831335]],

       [[ 0.449753  , -0.63880766,  1.08496735, -0.48391885,
          1.2545376 ],
        [ 0.44387976, -1.53317978,  1.11131447,  1.08923724,
         -0.32527169]]])

In [156]:
# soru : 15
soru15 = np.arange(0,51)
soru15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [160]:
soru15[20:36] = 500
soru15

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 500, 500, 500, 500, 500, 500,
       500, 500, 500, 500, 500, 500, 500, 500, 500, 500,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50])